DROP TABLE IF EXISTS VARS;

CREATE TEMP TABLE IF NOT EXISTS VARS
(
NAME TEXT PRIMARY KEY,
VAL INTEGER
);

INSERT INTO VARS(NAME,VAL)
VALUES("1P",(SELECT COUNT(*) FROM TEMPRPT)/2),
("2P",(SELECT COUNT(*) FROM TEMPRPT)),
("3P",3*(SELECT COUNT(*) FROM TEMPRPT)/2); 

--MEDIAN
INSERT INTO STATS
SELECT @type,@name as name,AVG(1.0*SALARY) as value
FROM (SELECT SALARY
      FROM TEMPRPT
      ORDER BY SALARY
      LIMIT 2 - (SELECT VAL FROM VARS WHERE NAME="2P") % 2
      OFFSET ((SELECT VAL FROM VARS WHERE NAME="2P") - 1) / 2) AS rptdata;